train_dataset:
  name: Soulart
  root_dir: /data/soulart_dataset
  n_joints: 21
  n_points: 256
  n_frames: 21
  mode: train

val_dataset:
  name: Soulart
  root_dir: /data/soulart_dataset
  n_joints: 21
  n_points: 256
  n_frames: 21
  mode: val

exp:
  title: movin_soulart
  path: /efs/exp_log/
  seed: 0
  batch_size: 32
  epochs: 30
  report_interval: 100
  lr: 0.0001
  resume_ckpt: None

model:
  in_chans: 9
  out_chans: 64