train_dataset:
  name: lidarhuman26M
  root_dir: /home/coder/project/DataA/lidarhuman26M/
  n_joints: 24
  n_points: 256
  n_frames: 4
  mode: train
  joint_coord_type: PST_v2

val_dataset:
  name: lidarhuman26M
  root_dir: /home/coder/project/DataA/lidarhuman26M/
  n_joints: 24
  n_points: 256
  n_frames: 4
  mode: val
  joint_coord_type: PST_v2

exp:
  title: ours_test_gcn_fix
  path: ./exp_log/
  seed: 0
  batch_size: 32
  epochs: 100
  report_interval: 10
  lr: 0.001
  resume_ckpt: None

model:
  num_sample_steps: 50
  point_encoder:
    point_bert: 
      pretrained: /home/coder/project/Point-BERT/experiments/Point-BERT_SURREAL_dvae_256_no_scaling/Mixup_models/pointBERT_pretrain_PST_sparse_256_no_scaling/ckpt-best.pth
      trans_dim: 384
      gcn_dim: 384
      depth: 12
      drop_path_rate: 0.1
      cls_dim: 512
      num_heads: 6
      group_size: 16
      num_group: 32
      encoder_dims: 256
    in_chans: 512
    hid_chans: 512
    out_chans: 512
    temporal_pos_enc_type: original 
    temporal_n_head: 8 
    temporal_n_layer: 2
    spatial_pos_enc_type: original
    spatial_n_head: 8
    spatial_n_layer: 2
    pooling_mode: avg
    drop_rate: 0.1

  imu_encoder:
    imu_chans: 9
    temporal_chans: 512
    out_chans: 256
    n_head: 8
    use_bn: True

  x_denoiser:
    n_joints: 24
    imu_chans: 3
    mlp: [256, 512, 512]
    cond_in_chans: 768
    n_head: 8
    qkv_chans: 256
    use_gcn: False
    use_leaky: True
    use_residual: True

  r_denoiser:
    n_joints: 24
    imu_chans: 6
    mlp: [256, 512, 512]
    cond_in_chans: 1024
    n_head: 8
    qkv_chans: 256
    use_gcn: False
    use_leaky: True
    use_residual: True
    x1_mapper:
      in_chans: 3
      out_chans: 256

  regressor:
    n_joints: 24
    imu_chans: 3
    mlp: [256, 256, 128]
    cond_in_chans: 768
    n_head: 8
    qkv_chans: 256
    use_gcn: False
    use_leaky: True
